### ISSUE TITLE
internal compiler error when building rmf_fleet_adapter

### ISSUE THREAD

**Issue by rcywongaa** [osrf/rmf_core#114]
When doing a clean `colcon build` on the current master, I get the following error
```
rmf_core/rmf_fleet_adapter/src/rmf_fleet_adapter/phases/../services/detail/impl_Negotiate.hpp:127:34: internal compiler error: in lambda_expr_this_capture, at cp/lambda.c:774
             [n = shared_from_this()]()
                  ~~~~~~~~~~~~~~~~^~
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
```

**Comment by Briancbn** [comment]
Same as #113, I think upgrading gcc will help you resolve the problem for now.
You can use the following lines to switch between versions, if you want to switch back.
```bash
sudo update-alternatives --config gcc
sudo update-alternatives --config g++
```

**Comment by mxgrey** [comment]
Alternatively, after installing g++8, you can use it to build with the following command:

```
CXX=g++-8 colcon build
```

**Comment by mxgrey** [comment]
Furthermore, for the best performance, I recommend building explicitly in release mode:

```
CXX=g++-8 colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release
```

**Comment by rcywongaa** [comment]
Thanks, not sure how it managed to build previously...
