### ISSUE TITLE
Unable to find `include/rmf_fleet_adapter` headers when using `ament_target_dependencies`

### ISSUE THREAD

**Issue by rcywongaa** [osrf/rmf_core#118]
Apologies if this is an issue of my poor CMake-fu and not an rmf_core thing...

I am following the advise here (https://github.com/osrf/rmf_core/issues/104#issuecomment-643994871) to create my own implementation of `RobotCommandHandle`.  However, I don't seem to be able to link and get the headers (`include/rmf_fleet_adapter/agv/RobotCommandHandle.hpp`) accessible in my node.

The relevant sections of my CMakeLists.txt
```
find_package(rclcpp REQUIRED)
find_package(rmf_fleet_adapter REQUIRED)

ament_target_dependencies(node
    rclcpp
    rmf_fleet_adapter
)

MESSAGE(WARNING "rmf_fleet_adapter_INCLUDE_DIRS = ${rmf_fleet_adapter_INCLUDE_DIRS}")
```
It shows that `rmf_fleet_adapter_INCLUDE_DIRS` only contains the following
```
  rmf_fleet_adapter_INCLUDE_DIRS =
  /opt/ros/eloquent/include;<dir_to_workspace>/install/rmf_traffic_msgs/include
```
which seems to be missing `rmf_fleet_adapter/include`.

I'm not sure what I'm doing wrong..

**Comment by mxgrey** [comment]
You shouldn't need to explicitly include the headers using `rmf_fleet_adapter_INCLUDE_DIRS`. Instead it should be sufficient to just do:

```
target_link_libraries(
  your_fleet_adapter
    PUBLIC
      rmf_fleet_adapter::rmf_fleet_adapter
)
```

With that, cmake should automatically include all the necessary headers for you. In modern cmake, this is known as "linking to an imported target". Let us know if that isn't working for you.

**Comment by rcywongaa** [comment]
I believe `ament_target_dependencies` already does that and is the recommended way as stated [here](https://index.ros.org/doc/ros2/Tutorials/Ament-CMake-Documentation/#adding-dependencies).  However, even with `ament_target_dependencies(my_fleet_adapter rmf_fleet_adapter)`, it still fails to find the required headers

**Comment by mxgrey** [comment]
I think `ament_target_dependencies` might only help with exporting the fact that your target depends on the imported target. I'm not sure that it actually takes care of the linking. Please put the code snippet of my previous reply into your cmake and let us know if it resolves the issue or not.

**Comment by mxgrey** [comment]
In fact the documentation you link indicates that `target_link_libraries` may still be necessary:

>  Sometimes it will be necessary to call the target_link_libaries CMake function. In the example of Eigen3, the call should then look like

```
find_package(Eigen3 REQUIRED)
target_link_libraries(my_target Eigen3::Eigen)
```

**Comment by rcywongaa** [comment]
Interestingly, I had to remove `ament_target_dependencies` and add `target_link_libraries` for it to work.
Having both gave me the error
```
CMake Error at CMakeLists.txt:42 (target_link_libraries):
  The plain signature for target_link_libraries has already been used with
  the target "node".  All uses of target_link_libraries with a target must be
  either all-keyword or all-plain.

  The uses of the plain signature are here:

   * /opt/ros/eloquent/share/ament_cmake_target_dependencies/cmake/ament_target_dependencies.cmake:65 (target_link_libraries)
```

Thanks a lot!

**Comment by mxgrey** [comment]
You should be able to include both by removing `PUBLIC` from the `target_link_libraries` call. It's unfortunate that ament doesn't support the `PUBLIC`/`PRIVATE` keywords yet, but I think that might be getting fixed in newer versions of ament.
