### ISSUE TITLE
Feature Request to cancel tasks

### ISSUE THREAD

**Issue by Geno117** [osrf/rmf_core#143]
It might be useful for end users to have the ability to cancel requests.
Just putting in a feature request for reference in the future.

Perhaps we could have an extra field in the task message like 
`string Status`

Potentially, there might be other actions an end user might want (perhaps change end location, change fleet to a more mobile one, etc.) and so it might be a good idea to leave a generic field for such operations.

**Comment by mxgrey** [comment]
Relevant PR: #274

**Comment by mxgrey** [comment]
I think we should keep this open until we're also able to cancel currently active tasks.

**Comment by mxgrey** [comment]
This feature request has been migrated over to https://github.com/open-rmf/rmf_ros2/issues/10
