### ISSUE TITLE
Vehicle still reverse after setting reversible to false in full control

### ISSUE THREAD

**Issue by Briancbn** [osrf/rmf_core#144]
Version used:
**rmf_core**: 1.0.2
**traffic editor**: 1.0.0
**rmf_demos**: https://github.com/osrf/rmf_demos/commit/dbe78f45973989283bac2b2451f93597a879094c

I simply added this line under [rmf_demos:magni_adapter.launch.xml](https://github.com/osrf/rmf_demos/blob/master/demos/launch/include/adapters/magni_adapter.launch.xml) and tested in simulation

```xml
      <arg name="reversible" value="false" />
```

The behaviour can be reproduced running [rmf_demos:office_loop_conflict.launch.xml](https://github.com/osrf/rmf_demos/blob/master/demos/launch/include/office/office_loop_conflict.launch.xml)

Although the fleet does not normally go back, but during the replanning and negotiation when conflicts are detected, the vehicle still reverse constantly. Is this an expected behaviour out of fleet adapter? or is there any way to avoid this problem.

**Comment by mxgrey** [comment]
This is a known issue in the simulation of the robot. The simulated robot isn't being told whether it's reversible, and it's not respecting the orientation command given to it by the fleet adapter.

This is an issue the should be addressed in the [traffic_editor](https://github.com/osrf/traffic_editor) repo.
