### ISSUE TITLE
Robot stops when reaching a certain point

### ISSUE THREAD

**Issue by MakinoharaShouko** [osrf/rmf_core#151]
I am running into a problem of a robot stop moving when reaching a point in the world.

Here is [the repo I am using](https://github.com/MakinoharaShouko/rmf_demos) and it is on master branch. The repo contains a new hotel conference level map. After cloning it to a rmf_demo_ws and doing `colcon build`, run `ros2 launch demos hotel.launch.xml`. In the RViZ panel, send a loop request to _mir100_ with _ballroom_back_ as both the start waypoint and the end waypoint. When the robot reaches the back door of the ballroom, it would stop moving as shown in the image below. And if you move it forward a little bit manually, it will be able to reach the destination.
![image](https://user-images.githubusercontent.com/57300801/90327605-16b8b880-df4a-11ea-84f7-48538f3f81d6.png)

I think this may have something to do with the door, because after trying the same request with the doors removed from the map, the robot could reach the destination on its own. And the robot's velocity also seemed to be faster.

I also tried to run it with only door ballroom_back1 (the door in front of which the robot stops) removed, and this time the robot stopped at the second door at the back of the ballroom

**Comment by mxgrey** [comment]
Yes, the robot is most likely stopping because of the doors. You should be able to see a printout in the Gazebo terminal to indicate this.

One thing that could help is to reduce the stopping parameters in the robot's sdf model. If it's possible to make the corridors wider, that could also help.

Ultimately the best solution is to make the simulation plugin of the robot less naive, but that will take some considerable work, because it may involve simulating sensors.

**Comment by tanyouliang95** [comment]
@MakinoharaShouko  Related to this fix, you will just need to reduce the stop distance of the gazebo robot model `slotcar_plugin`, which is defined [here](https://github.com/osrf/traffic_editor/blob/8b5f91b80ede1f555bfa61fce8c6b419c9c8fddd/building_sim_plugins/building_plugins_common/include/building_sim_common/slotcar_common.hpp#L166-L167). I managed to run this after tweaking it. Cheers

**Comment by mxgrey** [comment]
I'm closing this issue for lack of recent activity. Feel free to reopen if this is still an issue.
