### ISSUE TITLE
How do robots and the server running rmf_core communicate with one another?

### ISSUE THREAD

**Issue by lieuzhenghong** [osrf/rmf_core#170]
(I've tried to do my due diligence---but please chastise me appropriately if this question has a well-documented answer).

My team at IMDA is trying to augment RMF with new capabilities. My question is: _how do robots/doors/alarms communicate with the RMF core server?_ Is there some sort of HTTP REST API at the center of the core server? I understand that robots can talk to one another using the ROS [pub/sub system](https://index.ros.org/doc/ros2/Concepts/#id4), but what about non-ROS2 enabled devices like the server running RMF core/alarms/doors and so on?

My team needs to send some JSON objects from the robots to the central server, which (depending on what those JSON files say) will then reroute the robots or open lift doors or what not. I could of course set up my own robot-to-server communication (maybe with WebSockets), but I thought it might be a good idea to piggyback on whatever protocol OSRF is using.

Thanks very much for your time,
Zhenghong

**Comment by mxgrey** [comment]
No worries, this is a chastisement-free zone.

ROS2 is used for most of the communication that happens between fleet adapters, devices, and servers. For example, the traffic schedule server uses ROS2 to communicate with the fleet adapters to keep the schedule of robot motions up to date.

Of course we recognize that different middlewares have different strengths, so we also try to make it as easy as possible to hook other middlewares into RMF. Whenever possible we like to use [soss](https://github.com/osrf/soss) for that purpose. It supports translating a JSON websocket pub/sub system into ROS2 pub/sub. One application that is already using soss for this is the [romi-dashboard](https://github.com/osrf/romi-dashboard) that provides a web UI for watching the underlying operations of an RMF system.

**Comment by mxgrey** [comment]
Closing as this is not an issue. To continue discussing this topic, please open [a discussion](https://github.com/osrf/rmf_core/discussions).
