### ISSUE TITLE
Server sizing

### ISSUE THREAD

**Issue by cwrx777** [osrf/rmf_core#174]
Is there any guideline on how the server hosting RMF core adapters, fleet adapter implementation, and other adapters should be sized?

**Comment by mxgrey** [comment]
There aren't any official benchmarks at the moment.
 
So far all testing for fleet adapters has been done on typical desktop PC workstations. They're usually 8-16 CPU cores (or so-called "hyperthreads") and anywhere from 16-64GB of RAM.

Right now there's a known issue in the `rmf_traffic` planner where memory consumption can temporarily grow much much higher than it should really have to be (e.g. upwards of 10GB). We have plans to fix that issue, but it hasn't hit the top of our priority list yet, so for now I recommend using a machine that has at least 32GB of RAM.

**Comment by mxgrey** [comment]
Closing as this is not an issue. To continue discussing this topic, please open [a discussion](https://github.com/osrf/rmf_core/discussions).
