### ISSUE TITLE
Adding new observer+subscriber pair

### ISSUE THREAD

**Issue by txlei** [osrf/rmf_core#179]
goal is to edit the lift sequence listed in [rmf_rxcpp/design.md document](https://github.com/osrf/rmf_core/blob/master/rmf_fleet_adapter/rmf_rxcpp/design.md). 
eg. item1 after lift arrives, I wish to trigger a new next subscriber to get information of lift crowdedness and depending on the result, 
- either carry on to item2 move robot into lift, 
- or trigger next chain of observer_subscriber pair (i.e. cancel lift request -> request for lift again). 
this is for the use case where robot and passengers are allowed to co-share a lift. 

Would need advice on which files to modify the lift sequence, create new type of observer to lift crowdedness module (within RMF) and whether the existing templates available in [observer class](https://github.com/osrf/rmf_core/blob/master/rmf_fleet_adapter/rmf_rxcpp/RxCpp-4.1.0/Rx/v2/src/rxcpp/rx-observable.hpp) is sufficient for the described feature above.

**Comment by mxgrey** [comment]
I would suggest putting that logic into the `lift_supervisor` instead. The `lift_supervisor` is responsible for managing the "lift sessions" that determine which agent is using the lift at any given time.

If the lift supervisor is aware of the crowdedness of a lift, it could simply refuse to initiate a session with the AMR until people clear out of it.

A very simple prototype would be: Add a condition to [this if-statement](https://github.com/osrf/rmf_core/blob/1ca2c4d9f0ead4aa6d411d6baf5a29636d32b06e/rmf_fleet_adapter/src/lift_supervisor/Node.cpp#L74) that evaluates to `false` if the lift is too crowded to allow an AMR to enter.

I have plans to develop a "smart lift adapter", but I don't anticipate I'll have time to begin developing in earnest that until January.
