### ISSUE TITLE
running rmf in microservices in docker

### ISSUE THREAD

**Issue by imdalaf** [osrf/rmf_core#183]
So far, i have the impression that projects using rmf don't really run as microservices on docker. Not sure if this is right. If this is right, why so? Is it because of technical issue or are there other reasons such as speed and complexity?

**Comment by mxgrey** [comment]
We do run CI tests of entire RMF systems inside of docker.

I'm not aware of any current effort to isolate components of RMF into separate docker containers and then have those components work together in a single coherent system, but I'm also not aware of any technical limitations that would prevent that. It just takes a non-trivial amount of effort to configure docker containers to work across networks, and we haven't had a need to do that yet in our current phase of development.

If any RMF users would like to try dockerizing components of RMF, we'll be happy to take in contributions or feedback to address any issues that you encounter.

**Comment by imdalaf** [comment]
I see. Thanks for sharing.
