### ISSUE TITLE
Can we add an Actor on the taskSummary message?

### ISSUE THREAD

**Issue by matiasbavera** [osrf/rmf_core#205]
The objective of this is to append the `actor` of the `task` to the task's identifier (`task_id`) so as to be able to identify them in a graphical interface. Because just from the `task_id` it is very difficult to know what task it is without reading all the details.
Right now I'm getting the task's `actor`  from the `task.status` through regex in the interface, which does not seem like a good solution. Example of a state: `'Finding a plan for [tinyRobot/tinyRobot1] to go to [23] | Remaining phases: 6'`

Because a picture says more than a thousand words, I'm adding one to explain my point better =)

![untitled (2)](https://user-images.githubusercontent.com/11761240/98280603-67a0e180-1f7a-11eb-8db4-862ecb125df4.png)

My question here is if we can add an `actor` field to the message to append it to the task_id?.

**Current** `task_summary.msg `https://github.com/osrf/rmf_core/blob/master/rmf_task_msgs/msg/TaskSummary.msg

**Comment by koonpeng** [comment]
More explaination of the problem.

Currently we are using a regex to guess the actor from the status message. Obviously this is not reliable unless we somehow ensure that the message will always be in the same format. The `RobotState` has a task id but there is race condition as we might receive the task before it is updated on the robot state.

On a related topic should we also include multiple actors and actors of different types, e.g. identify the doors/lifts/dispenser etc associated with a task?

**Comment by mxgrey** [comment]
One tricky thing here is I can envision a future where some tasks are performed by multiple robots or multiple actors at once.

Perhaps there should be an `actors` array instead.

**Comment by matiasbavera** [comment]
> One tricky thing here is I can envision a future where some tasks are performed by multiple robots or multiple actors at once.
> 
> Perhaps there should be an `actors` array instead.

That's a good point, an array of actors should be fine.

**Comment by mxgrey** [comment]
Migrated to https://github.com/open-rmf/rmf_ros2/issues/40
