### ISSUE TITLE
Fleet adapter header files not exported

### ISSUE THREAD

**Issue by cnboonhan** [osrf/rmf_core#213]
It seems that for Fleet Adapters, certain header files are not exported into `install/rmf_fleet_adapter` and require relative paths: https://github.com/osrf/rmf_core/blob/master/rmf_fleet_adapter/src/mock_traffic_light/main.cpp#L19. It might be helpful to export these headers so that Fleet adapters can be developed outside of within the `rmf_core` folder.

**Comment by mxgrey** [comment]
Those are intentionally private because they're not meant to be part of the stable public API. We want to have flexibility to change those function definitions at any time without worrying about API or ABI compatibility.

I suppose we could consider providing an `unstable` namespace in the API and putting these utilities in there.

**Comment by cnboonhan** [comment]
Understand this. It might not be good to add unstable API, since end users will most likely experience build errors eventually. 

In this case, could we amend the workflow here https://osrf.github.io/ros2multirobotbook/integration_fleets.html to highlight the need for these private headers in addition to linking? From my experience, copying the headers in is enough. 

Just to avoid users assuming that linking the libraries all that is needed.

**Comment by mxgrey** [comment]
> to highlight the need for these private headers

I don't think these headers should generally be needed to create a fleet adapter. Their use is somewhat specific to creating a 100% ROS2 based fleet adapter, but I expect many system integrators will have their own preferred way to design their executables to parse arguments.

I think I would recommend using a library like `Boost.ProgramOptions` instead, or for Python-based implementations they should use `argparse`.

Is there some specific functionality from these headers that you think makes them worth bringing attention to?

**Comment by cnboonhan** [comment]
I dont think so. I think some users might assume the headers are available outside of the rmf_core package. In any case, this issue should point them in the right direction.

**Comment by mxgrey** [comment]
Oh, is the confusion because we point to the legacy full control fleet adapter as an example of a working fleet adapter?

**Comment by cnboonhan** [comment]
The content of the ros2multirobotbook is: 

The basic workflow of developing a fleet adapter is the following:

Create an application that links to the rmf_fleet_adapter library.

Have the application read in runtime parameters in whatever way is desired (e.g. command line arguments, configuration file, ROS parameters, REST API calls, environment variables, etc).

So it seems possible to think of developing a fleet adapter outside of rmf_core codebase. (perhaps just using the ros-foxy-rmf-* binaries)The first thing I would do might be to copy the examples out into an external folder to try it out, but this should break the build.

I think having a note on this detail ( in the example code , or on the ros2multirobotbook ) might help clarify this. ( That the headers are only necessary for pure ros2 adapters, for example )

**Comment by mxgrey** [comment]
I see, thanks for the perspective.

It would definitely be good for us to make a standalone minimal fleet adapter example that learners can trivially pick up and transplant into their own project.

**Comment by cnboonhan** [comment]
Thank you. I will close this for now.
