### ISSUE TITLE
use traffic-editor to create new office environment

### ISSUE THREAD

**Issue by Jason-Zhou1** [osrf/rmf_core#224]
Hi all,
I tried to use traffic-editor tool to create my own office environment. My project files are: myoffice.project.yaml, myoffice.building.yaml.
Then i run the following commands:
$ cd src/myofficesim/config/traffic-editor
$ ros2 run building_map_tools building_map_nav lobby.building.yaml .
Then I get error message:
No executable found
May I know what's wrong in my operation?

**Comment by mxgrey** [comment]
The issue page for `traffic-editor` can be found here: https://github.com/osrf/traffic_editor/issues

That being said, if you Google for `No executable found` and `ros2`, you'll find [this post](https://discourse.ros.org/t/ros2-cannot-run-my-python-script-no-executable-found-error/3912) which might be helpful.

I'll be closing this ticket as it's off-topic for this repo. If you need further assistance, the `traffic_editor` repo would be more appropriate than this repo.
