### ISSUE TITLE
Implement a reactive system for executing tasks queued by TaskManager

### ISSUE THREAD

**Issue by Yadunund** [osrf/rmf_core#231]
In the initial implementation of the task dispatcher system, a wall timer is used in the `TaskManager` to periodically check whether the next task should begin execution. As proposed in [this](https://github.com/osrf/rmf_core/pull/217#discussion_r540716132) review comment, we should instead implement this via a reactive system.

**Comment by mxgrey** [comment]
Migrated to https://github.com/open-rmf/rmf_ros2/issues/39
