### ISSUE TITLE
Have a way to clear out terminated tasks from memory

### ISSUE THREAD

**Issue by mxgrey** [osrf/rmf_core#238]
Related to https://github.com/osrf/rmf_core/pull/217#discussion_r545592368

**Comment by tanyouliang95** [comment]
Add a param `terminated_tasks_max_size` to set the size of "terminated task list". https://github.com/osrf/rmf_core/commit/01dc18151d461b9143ea49d3486613edffbb345a#r45362710

**Comment by mxgrey** [comment]
@tanyouliang95 Is it safe to close this issue?

**Comment by mxgrey** [comment]
Should be resolved in an upcoming PR

**Comment by tanyouliang95** [comment]
Yes! it is safe to close
