### ISSUE TITLE
Traffic light adapter with door and lift control

### ISSUE THREAD

**Issue by Kevinskwk** [osrf/rmf_core#239]
Hi! As far as I am aware, the current traffic light API is not capable of interacting with the infrastructure (please correct me if it is not the case). May I know if there is currently a way for robots integrated with the traffic light API to request doors/lifts when needed? Or will the _more advanced Traffic Light API that can automatically take care of this infrastructure interaction_ mentioned in #168 be available soon? Thank you!

**Comment by mxgrey** [comment]
> May I know if there is currently a way for robots integrated with the traffic light API to request doors/lifts when needed?

An API for that is not currently available. The fleet adapter which integrates with the traffic light API would also need to handle the message handshake exchange with the doors, lifts, and so on.

> Or will the more advanced Traffic Light API that can automatically take care of this infrastructure interaction mentioned in #168 be available soon?

This depends on your definition of "soon". I don't think it'll bubble up to the top of my priority list until late January. Once it reaches the top of the list, I would expect it to take 1-2 weeks to implement and test.

**Comment by Kevinskwk** [comment]
Understood. Thank you so much for your reply!

**Comment by webvenky** [comment]
Hi! Just wanted to check if there has been any update to the traffic light API that provides automatic interaction with lifts and doors?

**Comment by mxgrey** [comment]
Unfortunately other priorities have been jumping the queue, so that API hasn't been tackled yet. If I don't have any more curveballs, then I may be able to start on that by the end of this week.

**Comment by mxgrey** [comment]
Migrated to https://github.com/open-rmf/rmf_ros2/issues/38
