### ISSUE TITLE
Inserting custom sdf model in gazebo

### ISSUE THREAD

**Issue by destkk** [osrf/rmf_core#275]
Hi there. I have insert a new sdf model into rmf folder and also updated the traffic editor to spawn it.
However, after launching the world file `ros2 launch demos test_building_1.launch.xml` I am unable to launch the Gazebo program.
The following errors are shown below,
```
[gzclient-14] [Wrn] [Event.cc:61] Warning: Deleting a connection right after creation. Make sure to save the ConnectionPtr from a Connect call
[gzclient-14] [Err] [Connection.cc:546] Connection[16] Closed during Read
[gzclient-14] [Err] [TransportIface.cc:385] Unable to read from master
[gzclient-14] [Err] [GLWidget.cc:896] Unable to connect to a running Gazebo master.
[ERROR] [gzserver-13]: process has died [pid 30840, exit code -11, cmd 'gzserver --verbose -s libgazebo_ros_factory.so -s libgazebo_ros_init.so /home/home/rmf/install/rmf_demo_maps/share/rmf_demo_maps/maps/test_building_1/test_building_1.world'].
[gzclient-14] [Wrn] [Publisher.cc:136] Queue limit reached for topic /gazebo/world/user_camera/pose, deleting message. This warning is printed only once.
[gzclient-14] [Err] [gazebo_client.cc:56] Unable to setup Gazebo
[ERROR] [gzclient-14]: process has died [pid 32472, exit code 255, cmd 'gzclient --verbose /home/brobotics00/rmf/install/rmf_demo_maps/share/rmf_demo_maps/maps/test_building_1/test_building_1.world'].

```
May I know how to solve this issue?

**Comment by aaronchongth** [comment]
Hello @destkk!

> I have insert a new sdf model into rmf folder and also updated the traffic editor to spawn it.

Which folder are you referring to? Did you rebuild the `rmf_demo_maps` package after modifying it? You can do that by calling
```
rm -rf build/rmf_demo_maps install/rmf_demo_maps
colcon build --packages-select rmf_demo_maps
```
> I am unable to launch the Gazebo program.

Could you provide the whole terminal output after you start launching the world? This could give us a better idea of what went wrong.

As a sanity check, does this happen repeatedly every time you launch it?

**Comment by mxgrey** [comment]
I'll be closing this ticket due to inactivity.

To continue this discussion, I suggest opening a thread here: https://github.com/open-rmf/rmf/discussions
