### ISSUE TITLE
rmf_fleet_adapter build error

### ISSUE THREAD

**Issue by simk0024** [osrf/rmf_core#301]
Following error encountered while compiling rmf_core:
rmf_core/rmf_fleet_adapter/src/rmf_fleet_adapter/agv/TrafficLight.cpp:268:14: error: ‘class rmf_traffic::blockade::Participant’ has no member named ‘cancel’
rmf_core/rmf_fleet_adapter/src/rmf_fleet_adapter/agv/parse_graph.cpp:119:14: error: ‘class rmf_traffic::agv::Graph::Waypoint’ has no member named ‘set_charger’

**Comment by mxgrey** [comment]
It appears you're trying to use features that are introduced in the latest `master` branch, but you're building against an older version of `rmf_core`, probably version 1.2. You'll need to build `rmf_core` from source to use those features, instead of building your fleet adapter against the debian packages of the 21.01 release.

**Comment by simk0024** [comment]
Hi @mxgrey,
Those errors encountered when I am compiling `rmf_core` cloned from `master` branch?
Which is the stable release version compatible with `rmf_demos` and `free_fleet`? 
I follow the given instruction, but all have same issue when compiling the `rnf_fleet_adapter`.

**Comment by mxgrey** [comment]
I think you should try uninstalling your `ros-foxy-rmf-*` packages (`sudo apt-get remove ros-foxy-rmf-*`). We've encountered issues in the past where colcon/cmake is selecting the ROS distro version of `rmf_traffic` even though a version of it is in the workspace.

For reference, you can find the "missing" features [here](https://github.com/osrf/rmf_core/blob/67255072f4c1e8debcf85498c86ee4026fe240fd/rmf_traffic/include/rmf_traffic/blockade/Participant.hpp#L64-L67) and [here](https://github.com/osrf/rmf_core/blob/67255072f4c1e8debcf85498c86ee4026fe240fd/rmf_traffic/include/rmf_traffic/agv/Graph.hpp#L88) in the latest source code, so this is definitely a package version selection issue.

**Comment by simk0024** [comment]
Alright. Thank you @mxgrey
