### ISSUE TITLE
Dispatcher Bidding Result: has no submission during bidding

### ISSUE THREAD

**Issue by jamietjx** [osrf/rmf_core#305]
Hi everyone, i am having trouble trying to run the task for the tiny robot. The request was successfully submitted and assigned, however the dispatcher bidding result state that it has no submission during bidding. I am using my own simulation for this.
![Screenshot from 2021-03-01 10-44-34](https://user-images.githubusercontent.com/77659587/109445755-490bac80-7a7b-11eb-8e88-d8c6723383c3.png)
![Screenshot from 2021-03-01 10-44-34](https://user-images.githubusercontent.com/77659587/109445774-5032ba80-7a7b-11eb-9804-9255a269475f.png)

**Comment by Yadunund** [comment]
@jamietjx , please reopen your question as a Discussion item [here](https://github.com/osrf/rmf_core/discussions) as you are not reporting a bug in the codebase. In addition, describe your workspace setup and the commands used to launch your simulation. Do include the output of the terminal which launches your simulation. Without this, it is impossible to diagnose the problem.

**Comment by jamietjx** [comment]
Hi yadu,
I managed to solve the problem.
Thank you.

Regards,
Jamie Tan
