### ISSUE TITLE
full_control fleet adapter crashes when adding new robot

### ISSUE THREAD

**Issue by RValner** [osrf/rmf_core#315]
Hi,

I'm attempting to integrate rmf with free_fleet and initially I just want to get the basic pipeline working. Demos in [rmf_demos](https://github.com/osrf/rmf_demos) and [ff_examples](https://github.com/osrf/free_fleet) individually build and work fine. But when I tried to combine them, i.e., control the simulated turtlebot (via free_fleet demos) instead of the tinyRobot from the rmf_demos package, the `full_control` fleet adapter crashes as soon as the robot is registered.

I'm on Ubuntu 20.04 and the configuration of the demo pipeline is (launch files in the links):
turtlebot_sim(ROS Noetic) -> [free_fleet_client](https://github.com/osrf/free_fleet/blob/master/ff_examples_ros1/launch/turtlebot3_world_ff.launch)(ROS Noetic) -> [free_fleet_server](https://github.com/osrf/free_fleet/blob/master/ff_examples_ros2/launch/turtlebot3_world_ff.launch.xml)(ROS Foxy) -> [rmf_core](https://github.com/project-covsg24/free_fleet_rmf_example/blob/master/launch/tb3_world.launch.xml)(ROS Foxy)

If run the `full_control` node in GDB, it's saying that an uninitialized pointer is being accessed in the [`FleetUpdateHandle::Implementation::get_nearest_charger`](https://github.com/osrf/rmf_core/blob/6968346f40421d93039d898acdcbc3ca21f9ceeb/rmf_fleet_adapter/src/rmf_fleet_adapter/agv/FleetUpdateHandle.cpp#L746) method (or more percisely, the [pointer in here](https://github.com/osrf/rmf_core/blob/6968346f40421d93039d898acdcbc3ca21f9ceeb/rmf_traffic/src/rmf_traffic/agv/Planner.cpp#L318))

More [detailed backtrace here](https://gist.github.com/RValner/81ddfbded0154c895d8e368c765c5db6).

It might easily be that configurations in some of the above mentioned launch files just do not make sense but I'm out of ideas on what leads to this crash.

**Comment by aaronchongth** [comment]
Hello there @RValner!

Just a quick check, did you create and pass in a navigation graph of the turtlebot3 world for the fleet adapter? The examples in `ff_examples` do not come with their own navigation graph, which are required by the fleet adapters.

**Comment by RValner** [comment]
Hi, yes, I did generate a navigation graph via `ros2 run building_map_tools building_map_generator nav tb3_world.building.yaml .`. The source files and the resulting graph (0.yaml) [can be seen here](https://github.com/project-covsg24/free_fleet_rmf_example/tree/master/maps) and here's [the launch file that passes](https://github.com/project-covsg24/free_fleet_rmf_example/blob/master/launch/tb3_world.launch.xml) the graph to the fleet adapter.

**Comment by mxgrey** [comment]
Since it's crashing in the `get_nearest_charger` function, is it possible that your navigation graph is missing a charging waypoint, and that's leading to the crash?

If that's the issue, we should have the fleet adapter do something more sensible, like throw an exception with a clear explanation that the user is missing a charging point.

**Comment by RValner** [comment]
I have configured one of the navigation graph locations as a charger waypoint ([shown here](https://github.com/project-covsg24/free_fleet_rmf_example/blob/c348ffa7d5be8c4f35c6634607019ddb10a8a71f/maps/0.yaml#L62)) but unfortunately that did not change the error. Just to be clear, the nav graph is also copied to the install space during `colcon build`, so `ros2 launch` is fetching the up-to-date version of the navgraph.

**Comment by Yadunund** [comment]
Hi @RValner ,

I think the reasons for you segmentation fault is an empty `StartSet` passed into `FleetUpdateHandle::add_robot`. As a result, accessing `start[0]` inside the `get_nearest_charger()` method results in a crash. The `StartSet` is computed in the `full_control` implementation [here](https://github.com/osrf/rmf_core/blob/6968346f40421d93039d898acdcbc3ca21f9ceeb/rmf_fleet_adapter/src/full_control/main.cpp#L470-L472) using the `compute_plan_starts()` method.

There could be a couple of scenarios where the `compute_plan_starts()` method would return empty.
1. The `level_name` ( variable `state.location.level_name`) as reported in the `RobotState/FleetState` message does not match the level name in the supplied navigation graph.
2. The reported location (variable `{l.x, l.y, l.yaw}`) of the robot in the published `RobotState/FleetState` message is nowhere near any of the waypoints/lanes in the navigation graph. This could happen if your robot is not spawned near a navigation graph or if your coordinate transformation between the turtlebot and RMF frames is incorrect.
So could you check that these two points are valid? Kindly perform a sanity check of the `RobotState/FleetState` message published by `free_fleet`.

Additionally could you try computing the `StartSet` outside the `fleet->add_robot()` call [here](https://github.com/osrf/rmf_core/blob/6968346f40421d93039d898acdcbc3ca21f9ceeb/rmf_fleet_adapter/src/full_control/main.cpp#L472-L474)? Then you can check whether the result is really empty. If so, we would need to modify the `full_control` implementation to throw an error when this is the case.

**Comment by RValner** [comment]
Thanks @Yadunund, you're right, both the `level_name` in [free_fleet client launch file](https://github.com/open-rmf/free_fleet/blob/main/ff_examples_ros1/launch/turtlebot3_world_ff.launch) and the transformation in [server launch file](https://github.com/open-rmf/free_fleet/blob/main/ff_examples_ros2/launch/turtlebot3_world_ff.launch.xml) were incorrect. Seems that if either of the aforementioned variables is ill defined, the `full_control` fleet adapter will segfault. I guess this crash still probably not the intended behaviour as any faulty free_fleet client could potentially crash the adapter this way. But I got my problem solved and I'll close the issue.

Thanks a lot guys!
