### ISSUE TITLE
Have a better broad phase for trajectory conflict detection

### ISSUE THREAD

**Issue by mxgrey** [osrf/rmf_core#4]
I think it should be possible to analytically rule out trajectories that can't collide using one or more of the following techniques (I will add to this list as I think of more techniques):

* directly compute the maximum spatial reach of the trajectory as a bounding box
* directly compute the nearest distance that two trajectories come to each other (using calculus), and compare that to the extents of the collision shapes of each trajectory

**Comment by Jason-Zhou1** [comment]
Hi mxgrey,
May I know where is the cpp code for the conflict avoidance? I find the conflict detection code in the /rmf_traffic/Conflict.cpp file, but i haven't found the conflict avoidance part in any cpp files.
Thanks!
Jason

**Comment by mxgrey** [comment]
The collision avoidance for AGVs is achieved with a time-dependent A* search. The search takes time into account so that it can find paths through spacetime that account for the motions of other agents that are in the traffic schedule.

The entry point for the search can be found [on this line](https://github.com/osrf/rmf_core/blob/575a12c6e11e2e64c97a75f09aa24fc9b174d9b4/rmf_traffic/src/rmf_traffic/agv/internal_planning.cpp#L1352).

**Comment by mxgrey** [comment]
That being said, I think we can actually close this issue because it should be resolved as of #68.
