### ISSUE TITLE
Tasks are not getting queued 

### ISSUE THREAD

**Issue by MilanMichael** [osrf/rmf_core#98]
When i gave new tasks they are not being pushed to the queue, so i change the the following line 
https://github.com/osrf/rmf_core/blob/575a12c6e11e2e64c97a75f09aa24fc9b174d9b4/rmf_fleet_adapter/src/full_control/FleetAdapterNode.cpp#L173
to 
_task_queue.emplace_back(std::move(new_task));
and problem was solved

**Comment by mxgrey** [comment]
Thanks for catching this bug! The current fleet adapters are in the process of being completely rewritten, but this is a simple and important enough fix that I'll go ahead and push it in.

**Comment by mxgrey** [comment]
We can close this issue as the problem should be long solved now.
